# Generated by Django 3.2.9 on 2021-11-08 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=64, verbose_name='Логин')),
                ('password', models.CharField(max_length=64, verbose_name='Пароль')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='auth', to='board.user', verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'Счета',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateTimeField(verbose_name='Дата резервирования')),
            ],
            options={
                'verbose_name': 'Резервирование',
                'verbose_name_plural': 'Резервирования',
            },
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField(verbose_name='Номер шезлонга')),
                ('service', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='seats', to='board.service', verbose_name='Сервис')),
            ],
            options={
                'verbose_name': 'Шезлонг',
                'verbose_name_plural': 'Шезлонги',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.IntegerField(verbose_name='Номер билета')),
                ('number_persons', models.IntegerField(verbose_name='Количество персон')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
            },
        ),
        migrations.CreateModel(
            name='Vault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vault_number', models.IntegerField(verbose_name='Номер сейфа')),
                ('service', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='vault', to='board.service', verbose_name='Сервис')),
            ],
            options={
                'verbose_name': 'Сейф',
                'verbose_name_plural': 'Сейфы',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_visit', models.DateField(verbose_name='Дата')),
                ('service', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='visit', to='board.service', verbose_name='Сервис')),
                ('time', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='visit', to='board.time', verbose_name='Период')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='visit', to='board.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Посещение',
                'verbose_name_plural': 'Посещения',
            },
        ),
        migrations.RemoveField(
            model_name='chair',
            name='service',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='service',
        ),
        migrations.AddField(
            model_name='rate',
            name='description',
            field=models.TextField(default='', verbose_name='Описание тарифа'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Chair',
        ),
        migrations.AddField(
            model_name='ticket',
            name='rate',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='ticket', to='board.rate', verbose_name='Тариф'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='reservation',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='ticket', to='board.reservation', verbose_name='Резервирование'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='visit',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='ticket', to='board.visit', verbose_name='Посещение'),
        ),
        migrations.AddField(
            model_name='bill',
            name='rate',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='bill', to='board.rate', verbose_name='Тариф'),
        ),
        migrations.AddField(
            model_name='bill',
            name='ticket',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='bill', to='board.ticket', verbose_name='Билет'),
        ),
        migrations.AddField(
            model_name='bill',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='bill', to='board.user', verbose_name='Пользователь'),
        ),
    ]
