# Generated by Django 3.2.9 on 2021-11-08 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20211108_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='service',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='rate', to='board.service', verbose_name='Сервис'),
        ),
    ]
