# Generated by Django 3.2.9 on 2021-11-06 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Стоимость')),
                ('rate', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='price_rate', to='board.rate', verbose_name='Тариф')),
                ('service', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='price_rate', to='board.service', verbose_name='Сервис')),
            ],
        ),
    ]
