# Generated by Django 3.2.9 on 2021-11-06 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_pricerate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricerate',
            options={'verbose_name': 'Стоимость', 'verbose_name_plural': 'Стоимости'},
        ),
    ]
