# Generated by Django 3.2.9 on 2021-11-06 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_alter_pricerate_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер шезлонга')),
                ('service', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='chair', to='board.service', verbose_name='Шезлонг')),
            ],
            options={
                'verbose_name': 'Шезлонг',
                'verbose_name_plural': 'Шезлонги',
            },
        ),
    ]
