# Generated by Django 3.2.9 on 2021-11-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_auto_20211106_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='start_time',
            field=models.CharField(max_length=50, verbose_name='Время'),
        ),
    ]
