# Generated by Django 3.2.9 on 2021-11-06 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_alter_time_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rate',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='booking', to='board.pricerate', verbose_name='Тариф'),
        ),
    ]
